[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vicmd_symbol = "[](bold yellow)"

[ruby]
symbol = "◆ "

[nodejs]
disabled = true

[battery]
disabled = true

[package]
disabled = true

[dotnet]
format = "[$symbol($version )(-> $tfm )]($style)"

[aws]
disabled =true
