#!/usr/bin/env sh
# Opens the PR page for the current branch

if [ -d .git ] || git rev-parse --git-dir > /dev/null 2>&1; then
  url=$(git config remote.origin.url | sed -E "s~[^@]*@(.*):(.*)*\..*~https://\1/\2~")
  branch=$(git rev-parse --abbrev-ref HEAD)

  open "${url}/merge_requests/new?merge_request[source_branch=${branch}"
else
  echo "Not in a git repository."
fi
