#!/usr/bin/env bash
#
# Bootstraps a new script

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

usage() {
  local exit_code="${1:-1}"

  echo "Usage: newscript <filename>"

  exit $exit_code
}

BASE_DIR="$HOME/scripts"
TEMPLATE_PATH="$BASE_DIR/.template"

main() {
  local filename="${1:-}"

  if [[ -z "$filename" ]]; then usage; fi
  if [[ "$filename" = "--help" ]]; then usage 0; fi

  local full_path="$BASE_DIR/$filename"

  if [[ ! "-f $full_path" ]]; then
    echo "Script at $full_path already exists."
    exit 2
  fi

  # TODO
  vim "$full_path" -c "read $TEMPLATE_PATH | set ft=sh"
}

main "$@"
