#!/usr/bin/env bash
#
# Wrapper around xdg-open & /usr/bin/open to open stuff

set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
}

openCommand() {
  if command -v "/usr/bin/open" >/dev/null 2>&1; then
    echo "/usr/bin/open"
  else
    echo "xdg-open"
  fi
}

usage() {
  local exit_code="${1:-1}"

  echo "Usage: open <thing>"

  exit $exit_code
}

main() {
  local arg1="${1:-}"
  if [[ -z "$arg1" ]]; then usage; fi


  $(openCommand) "$arg1" &> /dev/null &
}

main "$@"
