#!/usr/bin/env bash
# Launches a new terminal. If the current terminal is a window,
# launches the new terminal in that terminal's pwd.

WINDOW_CLASS=`xprop WM_CLASS -id $(xdotool getactivewindow) | awk '{print $4}' | sed 's/"//g'`

if [[ "$WINDOW_CLASS" = "kitty" ]]; then
  WINDOW_PID=`xdotool getactivewindow getwindowpid`

  kitty @ --to "unix:/tmp/kitty-$WINDOW_PID" launch --type=os-window --cwd=current
else
  kitty
fi
