#!/usr/bin/env bash
# Simple wrapper for `pbcopy` which delegates
# to common UNIX utilities if it does not exist.

if command -v -p "pbcopy" > /dev/null; then
  command -p "pbcopy"
elif command -v "xsel" > /dev/null; then
  $(xsel --clipboard --input)
elif command -v "xclip" > /dev/null; then
  $(xclip -selection clipboard)
fi
