#!/usr/bin/env bash
# Simple wrapper for `pbpaste` which delegates
# to common UNIX utilities if it does not exist.

if command -v -p "pbpaste" > /dev/null; then
  command -p "pbpaste"
elif command -v "xsel" > /dev/null; then
  $(xsel --clipboard --output)
elif command -v "xclip" > /dev/null; then
  $(xclip -selection clipboard -o)
fi
