#!/usr/bin/env bash
# Loads environment variables for pim use.
# Should not be sourced in a regular shell, but run in a subshell for a particular program.

PERSONAL_MAIL_SECRETS=$(secret-tool search Path "Personal Mail" 2>&1 | tail -n +2)
WORK_MAIL_SECRETS=$(secret-tool search Path "Work Mail" 2>&1 | tail -n +2)

PERSONAL_CALENDAR_SECRETS=$(secret-tool search Path "Personal Calendar" 2>&1 | tail -n +2)
SPOUSE_CALENDAR_SECRETS=$(secret-tool search Path "Spouse Calendar" 2>&1 | tail -n +2)

PERSONAL_CONTACTS_SECRETS=$(secret-tool search Path "Personal Contacts" 2>&1 | tail -n +2)

function secret() {
  local secrets_output="$1"
  local key="$2"

  echo "$secrets_output" | grep "$key" -m 1 | awk -F' = ' '{print $2}'
}

export MAIL_WORK_IMAP_HOST=$(secret "$WORK_MAIL_SECRETS" "imap_host")
export MAIL_WORK_SMTP_HOST=$(secret "$WORK_MAIL_SECRETS" "smtp_host")
export MAIL_WORK_SMTP_PORT=$(secret "$WORK_MAIL_SECRETS" "smtp_port")
export MAIL_WORK_USERNAME=$(secret "$WORK_MAIL_SECRETS" "UserName")
export MAIL_WORK_PASSWORD=$(secret "$WORK_MAIL_SECRETS" "secret")

export MAIL_PERSONAL_IMAP_HOST=$(secret "$PERSONAL_MAIL_SECRETS" "imap_host")
export MAIL_PERSONAL_SMTP_HOST=$(secret "$PERSONAL_MAIL_SECRETS" "smtp_host")
export MAIL_PERSONAL_SMTP_PORT=$(secret "$PERSONAL_MAIL_SECRETS" "smtp_port")
export MAIL_PERSONAL_USERNAME=$(secret "$PERSONAL_MAIL_SECRETS" "UserName")
export MAIL_PERSONAL_PASSWORD=$(secret "$PERSONAL_MAIL_SECRETS" "secret")

export PERSONAL_CALENDAR_USERNAME=$(secret "$PERSONAL_CALENDAR_SECRETS" "UserName")
export PERSONAL_CALENDAR_PASSWORD=$(secret "$PERSONAL_CALENDAR_SECRETS" "secret")
export PERSONAL_CALENDAR_URL=$(secret "$PERSONAL_CALENDAR_SECRETS" "URL")
export PERSONAL_CALENDAR_ID=$(basename $PERSONAL_CALENDAR_URL)

export SPOUSE_CALENDAR_USERNAME=$(secret "$SPOUSE_CALENDAR_SECRETS" "UserName")
export SPOUSE_CALENDAR_PASSWORD=$(secret "$SPOUSE_CALENDAR_SECRETS" "secret")
export SPOUSE_CALENDAR_URL=$(secret "$SPOUSE_CALENDAR_SECRETS" "URL")
export SPOUSE_CALENDAR_ID=$(basename $SPOUSE_CALENDAR_URL)

export PERSONAL_CONTACTS_USERNAME=$(secret "$PERSONAL_CONTACTS_SECRETS" "UserName")
export PERSONAL_CONTACTS_PASSWORD=$(secret "$PERSONAL_CONTACTS_SECRETS" "secret")
export PERSONAL_CONTACTS_URL=$(secret "$PERSONAL_CONTACTS_SECRETS" "URL")
export PERSONAL_CONTACTS_ID=$(basename $PERSONAL_CONTACTS_URL)
