#!/usr/bin/env sh
# Script to fetch and index mail
echo -e "\033[36mSyncing mail...\033[0m"
mbsync $@

echo -e "\n\033[36mTagging mail...\033[0m"
notmuch new 2&>/dev/null && tagmail

echo -e "\n\033[32mDone!\033[0m"
