#!/usr/bin/env sh
# Script to fetch and index mail
echo -e "\033[36mSyncing mail...\033[0m"
mbsync $@

echo -e "\n\033[36mIndexing personal mail...\033[0m"
mu personal index

echo -e "\n\033[36mIndexing work mail...\033[0m"
mu work index

echo -e "\n\033[32mDone!\033[0m"
