#!/usr/bin/env sh
# Navigates between panes in tmux and vim

command=$1

function is_vim {
  [[ $(tmux display -p '#{pane_current_command}') =~ n?vim ]] && return 0

  return 1
}

function left {
  if is_vim; then
    tmux send-keys C-h
  else
    tmux select-pane -L
  fi
}

function right {
  if is_vim; then
    tmux send-keys C-l
  else
    tmux select-pane -R
  fi
}

function up {
  if is_vim; then
    tmux send-keys C-k
  else
    tmux select-pane -U
  fi
}

function down {
  if is_vim; then
    tmux send-keys C-j
  else
    tmux select-pane -D
  fi
}

function last {
  if is_vim; then
    tmux send-keys C-\\
  else
    tmux select-pane -l
  fi
}

function command_not_found {
  echo 'Usage: tmux-vim-navigate [up|down|left|right|last]'
  exit 1
}

case "${command}" in
  left) left;;
  right) right;;
  up) up;;
  down) down;;
  last) last;;
  *)
    command_not_found
esac
