#!/usr/bin/env sh

COMMAND=$1
UNIT=5

case $COMMAND in
  up )
    pamixer -i $UNIT && notify-send -h string:x-canonical-private-synchronous:volume $(pamixer --get-volume-human)
    ;;
  down )
    pamixer -d $UNIT && notify-send -h string:x-canonical-private-synchronous:volume $(pamixer --get-volume-human)
    ;;
  mute )
    pamixer -t $UNIT && notify-send -h string:x-canonical-private-synchronous:volume $(pamixer --get-volume-human)
    ;;
esac

case word in
  pattern )
    ;;
esac
