" vimrc is only used to source stuff.
" for config, see ~/.vim/config or
" fuzzy find with <leader>fev
source $HOME/.vim/config/000_library.vim
source $HOME/.vim/config/001_functions.vim
source $HOME/.vim/config/010_bundles.vim
source $HOME/.vim/config/020_basics.vim
source $HOME/.vim/config/030_commands.vim
source $HOME/.vim/config/040_languages.vim

if has('nvim')
  source $HOME/.vim/config/050_neovim.vim
endif

source $HOME/.vim/config/060_autocmd.vim
source $HOME/.vim/config/070_style.vim

" Bundle settings
call SourceDir("$HOME/.vim/config/bundles/")
call SourceDir("$HOME/.vim/config/mappings/")
