" Indentation
set autoindent
set smartindent
set nostartofline
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab

" Avoid backup mess (.doc.swp, ~.doc) by moving backups tmp
set backupcopy=yes
set backupdir=/tmp
set directory=/tmp

" Case insensitive search
set hlsearch
set ignorecase
set smartcase

" Open new splits to right and bottom
set splitbelow
set splitright

" Temporarily disable search highlighting when in insert mode.
autocmd InsertEnter * :setlocal nohlsearch
autocmd InsertLeave * :setlocal hlsearch

" Use a transparent background
hi Normal guibg=NONE

" Remap 0 to ^ (first char in line)
map 0 ^

" Switch ;/: for easier command entry.
nnoremap : ;
nnoremap ; :
vnoremap : ;
vnoremap ; :

" Window navigation
nnoremap <silent> <C-h> :wincmd h<CR>
nnoremap <silent> <C-j> :wincmd j<CR>
nnoremap <silent> <C-k> :wincmd k<CR>
nnoremap <silent> <C-l> :wincmd l<CR>

let mapleader = " "

nnoremap <Leader><TAB> <C-^>
