#!/usr/bin/env bash
# From https://codeberg.org/EvanHahn/dotfiles/src/commit/843b9ee13d949d346a4a73ccee2a99351aed285b/home/bin/bin/copy
set -e
set -u

if [ $# -gt 0 ]; then
  exec < "$1"
fi

if hash pbcopy 2>/dev/null; then
  exec pbcopy
elif hash xclip 2>/dev/null; then
  exec xclip -selection clipboard
elif hash putclip 2>/dev/null; then
  exec putclip
else
  cat >/tmp/clipboard
fi
